                <div id="footerDiv">
                    <div class="leftSide"></div>
                    <div class="rightSide"></div>
                    <table style="height : 100%; color : #ffffff;"><tr>
                        <td></td>
                        <td style="width : 870px; color : #b5c7d6; font-style : italic; padding-top : 0px; ">This site is maintained by the UNEP/EUROBATS Secretariat. © <?php echo date("Y"); ?> UNEP/EUROBATS</td>
                        <td><a href="http://www.unep.org/" target="_blank">
                            <img src="/<?php print $directory; ?>/img/UNEP.png" alt="UNEP" title="UNEP" /></a></td>
                        <td>
                            <a href="http://www.eurobats.org/">
                            <img src="/<?php print $directory; ?>/img/EUROBATS.png" alt="EUROBATS" title="EUROBATS" /></a></td>
                    </tr></table>
                </div>




            </div>
        </div>
    </div>
<?php
if ( $is_front ) {
?>
    <div style="clear : both; height : 236px;"></div>
<?php
}
else {
?>
    <div style="clear : both; height : 1px;"></div>
<?php
}
?>
</div>
